name: Daily Playwright Tests - Staging Environment

trigger: none
pr: none

schedules:
  # Winter: Jan–Mar (Mon–Fri at 07:00 UTC = 07:00 UK) Monday to Friday
  - cron: "0 7 * 1-3 1-5"
    displayName: "Weekday 7AM Run (Winter UK Time - Jan to Mar)"
    branches:
      include:
        - master
    always: true

  # Summer: Apr–Oct (Mon–Fri at 06:00 UTC = 07:00 UK) Monday to Friday
  - cron: "0 6 * 4-10 1-5"
    displayName: "Weekday 7AM Run (Summer UK Time - Apr to Oct)"
    branches:
      include:
        - master
    always: true

  # Winter: Nov–Dec (Mon–Fri at 07:00 UTC = 07:00 UK) Monday to Friday
  - cron: "0 7 * 11-12 1-5"
    displayName: "Weekday 7AM Run (Winter UK Time - Nov to Dec)"
    branches:
      include:
        - master
    always: true         

pool:
  name: 'hmcts-sds-ptl'

steps:
  - checkout: self

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'DTS-SHAREDSERVICES-TEST'
      KeyVaultName: 'pre-hmctskv-test'
      SecretsFilter: 'pre-level-1-test-login-email,pre-level-1-test-login-password,cvp-settings-base-url,cvp-conference-base-url,cvp-user-login-email,cvp-user-login-password,cvp-conference-user-email,cvp-service-id,cvp-location-code'
    displayName: 'Fetch Common Secrets From Azure Key Vault'  
  
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'DTS-SHAREDSERVICES-STG-Pre-Recorded Evidence'
      KeyVaultName: 'pre-hmctskv-stg'
      SecretsFilter: 'pre-power-app-base-url,pre-api-url'
    displayName: 'Fetch Env Specific Secrets From Azure Key Vault'

  - script: |
      yarn install
      yarn setup
      yarn playwright install msedge
    displayName: 'Install dependencies and Playwright browsers'

  - script: |
        yarn playwright test 
    displayName: 'Run Playwright tests'
    env:
      CI: 'true'
      FUNCTIONAL_TESTS_WORKERS: '4'
      BASE_URL: $(pre-power-app-base-url)
      API_URL: $(pre-api-url)
      PRE_LEVEL_1_USER_EMAIL: $(pre-level-1-test-login-email)
      PRE_LEVEL_1_USER_PASSWORD: $(pre-level-1-test-login-password)
      CVP_SETTINGS_BASE_URL: $(cvp-settings-base-url)
      CVP_CONFERENCE_BASE_URL: $(cvp-conference-base-url)
      CVP_USER_EMAIL: $(cvp-user-login-email)
      CVP_USER_PASSWORD: $(cvp-user-login-password)
      CVP_CONFERENCE_USER_EMAIL: $(cvp-conference-user-email)
      CVP_SERVICE_ID: $(cvp-service-id)
      CVP_LOCATION_CODE: $(cvp-location-code)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report'
      artifact: 'PlaywrightHTMLReport'
      publishLocation: 'pipeline'
    displayName: 'Publish Playwright HTML Report and assets'
    condition: succeededOrFailed()